version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    working_directory: ~/devops-groupproject
    docker:
      #putting in a ruby image instead of the node one in my CA
      - image: circleci/ruby:3.0
    steps:
      - checkout
      - run:
          #update bundler for ruby instead of npm 
          name: update-bundler
          command: 'gem install bundler'
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
      - run:
          #install bundle
          name: install-bundle
          command: bundle install
      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

  deploy:
    docker: 
      - image:  circleci/ruby:3.0
    steps:
      - run:
        name: deploy-application
        command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf devops-groupproject/; git clone https://github.com/ailsapm/devops-groupproject.git; source devops-groupproject/deploy.sh"
